[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.24"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../frontend/integration/keys/funder_private_key.json"

[programs.localnet]
token_dispenser = "Wapg5wZgUZUj8UrLKiruTiC2LwT68g2i93UrrJ2poga"

[programs.mainnet]
token_dispenser = "Wapg5wZgUZUj8UrLKiruTiC2LwT68g2i93UrrJ2poga"

[programs.devnet]
token_dispenser = "Wapg5wZgUZUj8UrLKiruTiC2LwT68g2i93UrrJ2poga"

[scripts]
test = "cargo test-bpf"
export = "anchor build && ./scripts/export_idl.sh"
