name: Backend Tests
on:
  pull_request:
    paths: [backend/**]
  push:
    branches: [main]
    paths: [backend/**]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: backend/yarn.lock
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Prettier check
        run: yarn prettier:check
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
